include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    unused_import: ignore
    unused_element: ignore
    unused_local_variable: ignore
    unused_element_parameter: ignore
    unnecessary_cast: ignore
    unnecessary_to_list_in_spreads: ignore
    unnecessary_brace_in_string_interps: ignore
    deprecated_member_use: ignore
    curly_braces_in_flow_control_structures: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    prefer_single_quotes: true
    use_super_parameters: true
