import '../models/kana_character.dart';

class KanaCatalog {
  static final hiragana = _build(
    basic: 'あいうえおかきくけこさしすせそたちつてとなにぬねの'
        'はひふへほまみむめもやゆよらりるれろわをん',
    voiced: 'がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ',
    combinations: const [
      'きゃ',
      'きゅ',
      'きょ',
      'しゃ',
      'しゅ',
      'しょ',
      'ちゃ',
      'ちゅ',
      'ちょ',
      'にゃ',
      'にゅ',
      'にょ',
      'ひゃ',
      'ひゅ',
      'ひょ',
      'みゃ',
      'みゅ',
      'みょ',
      'りゃ',
      'りゅ',
      'りょ',
      'ぎゃ',
      'ぎゅ',
      'ぎょ',
      'じゃ',
      'じゅ',
      'じょ',
      'びゃ',
      'びゅ',
      'びょ',
      'ぴゃ',
      'ぴゅ',
      'ぴょ',
    ],
  );

  static final katakana = _build(
    basic: 'アイウエオカキクケコサシスセソタチツテトナニヌネノ'
        'ハヒフヘホマミムメモヤユヨラリルレロワヲン',
    voiced: 'ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ',
    combinations: const [
      'キャ',
      'キュ',
      'キョ',
      'シャ',
      'シュ',
      'ショ',
      'チャ',
      'チュ',
      'チョ',
      'ニャ',
      'ニュ',
      'ニョ',
      'ヒャ',
      'ヒュ',
      'ヒョ',
      'ミャ',
      'ミュ',
      'ミョ',
      'リャ',
      'リュ',
      'リョ',
      'ギャ',
      'ギュ',
      'ギョ',
      'ジャ',
      'ジュ',
      'ジョ',
      'ビャ',
      'ビュ',
      'ビョ',
      'ピャ',
      'ピュ',
      'ピョ',
    ],
  );

  static const _basicRomaji = [
    'a',
    'i',
    'u',
    'e',
    'o',
    'ka',
    'ki',
    'ku',
    'ke',
    'ko',
    'sa',
    'shi',
    'su',
    'se',
    'so',
    'ta',
    'chi',
    'tsu',
    'te',
    'to',
    'na',
    'ni',
    'nu',
    'ne',
    'no',
    'ha',
    'hi',
    'fu',
    'he',
    'ho',
    'ma',
    'mi',
    'mu',
    'me',
    'mo',
    'ya',
    'yu',
    'yo',
    'ra',
    'ri',
    'ru',
    're',
    'ro',
    'wa',
    'wo',
    'n',
  ];

  static const _voicedRomaji = [
    'ga',
    'gi',
    'gu',
    'ge',
    'go',
    'za',
    'ji',
    'zu',
    'ze',
    'zo',
    'da',
    'ji',
    'zu',
    'de',
    'do',
    'ba',
    'bi',
    'bu',
    'be',
    'bo',
    'pa',
    'pi',
    'pu',
    'pe',
    'po',
  ];

  static const _combinationRomaji = [
    'kya',
    'kyu',
    'kyo',
    'sha',
    'shu',
    'sho',
    'cha',
    'chu',
    'cho',
    'nya',
    'nyu',
    'nyo',
    'hya',
    'hyu',
    'hyo',
    'mya',
    'myu',
    'myo',
    'rya',
    'ryu',
    'ryo',
    'gya',
    'gyu',
    'gyo',
    'ja',
    'ju',
    'jo',
    'bya',
    'byu',
    'byo',
    'pya',
    'pyu',
    'pyo',
  ];

  static List<KanaCharacter> _build({
    required String basic,
    required String voiced,
    required List<String> combinations,
  }) {
    final output = <KanaCharacter>[];
    final basicChars = basic.runes.map(String.fromCharCode).toList();
    final voicedChars = voiced.runes.map(String.fromCharCode).toList();
    for (var index = 0; index < basicChars.length; index++) {
      output.add(
        KanaCharacter(
          character: basicChars[index],
          romaji: _basicRomaji[index],
          group: 'Dasar',
        ),
      );
    }
    for (var index = 0; index < voicedChars.length; index++) {
      output.add(
        KanaCharacter(
          character: voicedChars[index],
          romaji: _voicedRomaji[index],
          group: 'Dakuten',
        ),
      );
    }
    for (var index = 0; index < combinations.length; index++) {
      output.add(
        KanaCharacter(
          character: combinations[index],
          romaji: _combinationRomaji[index],
          group: 'Yōon',
        ),
      );
    }
    return List.unmodifiable(output);
  }
}
