class MeaningLocalizer {
  const MeaningLocalizer._();

  static String cleanId(String value) {
    var text = value.trim();
    if (text.isEmpty) return text;

    final exact = _exact[text.toLowerCase()];
    if (exact != null) return exact;

    for (final entry in _phrases.entries) {
      text = text.replaceAll(entry.key, entry.value);
      text = text.replaceAll(_capitalize(entry.key), _capitalize(entry.value));
    }
    for (final entry in _words.entries) {
      final pattern = RegExp('\\b${entry.key}\\b', caseSensitive: false);
      text = text.replaceAllMapped(pattern, (_) => entry.value);
    }

    text = text
        .replaceAll('[v.i.]', '(verba intransitif)')
        .replaceAll('[v.t.]', '(verba transitif)')
        .replaceAll('[hon.]', '(hormat)')
        .replaceAll('e.g.', 'misalnya')
        .replaceAll('i.e.', 'yaitu')
        .replaceAll('etc.', 'dan sebagainya')
        .replaceAll('~', '～');
    text = text.replaceAll(RegExp(r'\s+'), ' ').trim();
    return text;
  }

  static String _capitalize(String value) => value.isEmpty
      ? value
      : '${value[0].toUpperCase()}${value.substring(1)}';

  static const Map<String, String> _exact = {
    'man, male': 'laki-laki, pria',
    'woman, female': 'perempuan, wanita',
    'year, age': 'tahun, usia',
    'free time, leisure': 'waktu luang',
    'family, members of a family': 'keluarga, anggota keluarga',
    'home, family': 'rumah, keluarga',
    'river, stream': 'sungai, aliran air',
    'big, great': 'besar, hebat',
    'new, fresh': 'baru, segar',
    'old days, past': 'masa lalu, zaman dulu',
    'human being, person': 'manusia, orang',
    'wealthy person, millionaire': 'orang kaya, jutawan',
    'boiling water': 'air mendidih',
    'canned food, tinned food': 'makanan kaleng',
  };

  static const Map<String, String> _words = {
    'to': 'untuk',
    'of': 'dari',
    'in': 'di',
    'the': '',
    'for': 'untuk',
    'and': 'dan',
    'or': 'atau',
    'with': 'dengan',
    'from': 'dari',
    'at': 'di',
    'as': 'sebagai',
    'by': 'oleh',
    'on': 'di',
    'be': 'menjadi',
    'have': 'memiliki',
    'get': 'mendapat',
    'go': 'pergi',
    'come': 'datang',
    'take': 'mengambil',
    'make': 'membuat',
    'put': 'meletakkan',
    'turn': 'berbelok',
    'break': 'istirahat/rusak',
    'open': 'membuka',
    'close': 'menutup',
    'return': 'kembali',
    'raise': 'menaikkan',
    'wear': 'memakai',
    'hit': 'memukul',
    'strike': 'memukul',
    'play': 'bermain',
    'work': 'pekerjaan',
    'business': 'bisnis',
    'school': 'sekolah',
    'family': 'keluarga',
    'person': 'orang',
    'people': 'orang-orang',
    'someone': 'seseorang',
    'thing': 'benda/hal',
    'things': 'benda/hal',
    'something': 'sesuatu',
    'house': 'rumah',
    'home': 'rumah',
    'office': 'kantor',
    'place': 'tempat',
    'side': 'sisi',
    'point': 'titik',
    'time': 'waktu',
    'day': 'hari',
    'days': 'hari',
    'month': 'bulan',
    'year': 'tahun',
    'years': 'tahun',
    'old': 'tua/lama',
    'new': 'baru',
    'young': 'muda',
    'all': 'semua',
    'entire': 'seluruh',
    'one': 'satu',
    'number': 'angka/jumlah',
    'counter': 'kata hitung',
    'money': 'uang',
    'rice': 'nasi/beras',
    'food': 'makanan',
    'water': 'air',
    'fire': 'api',
    'tree': 'pohon',
    'wood': 'kayu',
    'mountain': 'gunung',
    'river': 'sungai',
    'road': 'jalan',
    'street': 'jalan',
    'hand': 'tangan',
    'face': 'wajah/menghadap',
    'hair': 'rambut/bulu',
    'heart': 'hati',
    'mind': 'pikiran',
    'body': 'tubuh',
    'mouth': 'mulut',
    'eye': 'mata',
    'ear': 'telinga',
    'root': 'akar',
    'roof': 'atap',
    'sword': 'pedang',
    'class': 'kelas',
    'student': 'siswa',
    'teacher': 'guru',
    'university': 'universitas',
    'weather': 'cuaca',
    'sunny': 'cerah',
    'rainy': 'hujan',
    'cloudy': 'mendung',
    'hot': 'panas',
    'cold': 'dingin',
    'later': 'nanti/kemudian',
    'future': 'masa depan',
    'next': 'berikutnya/sebelah',
    'door': 'pintu',
    'height': 'tinggi badan',
    'stature': 'perawakan',
    'above': 'atas',
    'below': 'bawah',
    'up': 'atas',
    'down': 'bawah',
    'out': 'keluar',
    'off': 'lepas',
    'away': 'jauh',
    'hard': 'keras',
    'soft': 'lembut',
    'festival': 'festival',
    'control': 'kontrol/pengaruh',
    'influence': 'pengaruh',
    'form': 'bentuk',
    'humble': 'rendah hati/sopan',
    'honorific': 'bentuk hormat',
    'style': 'gaya',
    'state': 'keadaan',
    'method': 'cara',
    'way': 'cara',
    'language': 'bahasa',
    'japanese': 'bahasa Jepang',
    'chinese': 'Tionghoa/Cina',
    'character': 'karakter/huruf',
    'foreign': 'asing',
  };

  static const Map<String, String> _phrases = {
    'to play': 'bermain',
    'to spend time pleasantly': 'menghabiskan waktu dengan menyenangkan',
    'cloudiness': 'keadaan mendung',
    'cloudy weather': 'cuaca mendung',
    'counter for small items': 'kata hitung untuk benda kecil',
    'counter for small animals': 'kata hitung untuk hewan kecil',
    'years old': 'tahun',
    "o'clock": 'jam',
    'to make sound': 'mengeluarkan suara',
    'clear (sunny) weather': 'cuaca cerah',
    'fine weather': 'cuaca baik',
    'rainy weather': 'cuaca hujan',
    'late afternoon': 'sore menjelang malam',
    'evening': 'malam',
    'mountain range': 'pegunungan',
    'rocky mountain': 'gunung berbatu',
    'southern mountain': 'gunung selatan',
    'small stream': 'sungai kecil',
    'brook': 'anak sungai',
    'right-hand man': 'orang kepercayaan',
    'cram school': 'tempat bimbingan belajar',
    'middle-aged man': 'pria paruh baya',
    'arm': 'lengan',
    'body': 'tubuh',
    'specialized in': 'ahli dalam',
    'entry to school': 'masuk sekolah',
    'university': 'universitas',
    'old haunts': 'tempat lama yang sering dikunjungi',
    'former homes': 'rumah lama',
    'construction work': 'pekerjaan konstruksi',
    'flesh': 'daging',
    "person's identity": 'identitas seseorang',
    'surname': 'nama keluarga',
    'family name': 'nama keluarga',
    'person in charge': 'penanggung jawab',
    'meals': 'makanan',
    'food': 'makanan',
    'term': 'periode',
    'school': 'sekolah',
    'subject': 'mata pelajaran',
    'curriculum': 'kurikulum',
    'temperature': 'suhu',
    'present-day': 'masa kini',
    'school building': 'gedung sekolah',
    'individual': 'individu',
    'private person': 'orang pribadi',
    'work': 'pekerjaan',
    'operation': 'operasi',
    'labor': 'tenaga kerja',
    'organ': 'organ',
    'coins': 'koin',
    'small change': 'uang receh',
    'whole body': 'seluruh tubuh',
    'full-length': 'seluruh badan',
    'convention': 'konvensi',
    'tournament': 'turnamen',
    'stranger': 'orang asing',
    'course': 'kursus',
    'unit': 'satuan',
    'commuting to school': 'pergi-pulang sekolah',
    'commuting to work': 'pergi-pulang kerja',
    'simultaneous': 'serentak',
    'same time': 'waktu yang sama',
    'independence': 'kemerdekaan',
    'mountain-climbing': 'mendaki gunung',
    'mountain climbing': 'mendaki gunung',
    'old people': 'orang tua/lansia',
    'the aged': 'lansia',
    'farmer': 'petani',
    'farm family': 'keluarga petani',
    'lost child': 'anak hilang',
    'dropping out of school': 'putus sekolah',
    'appointment': 'janji temu',
    'leisure': 'waktu luang',
    'alarm bell': 'bel alarm',
    'fire bell': 'bel kebakaran',
    'old age': 'usia tua',
    'young woman': 'perempuan muda',
    'pregnant woman': 'perempuan hamil',
    'married woman': 'perempuan menikah',
    'New Year': 'Tahun Baru',
    'Japanese': 'bahasa Jepang',
    'translation': 'terjemahan',
    'title': 'judul',
    'foreign': 'asing',
    'wealthy': 'kaya',
    'pass': 'berlalu',
    'spend': 'menghabiskan',
    'sleeping': 'tidur',
    'working hours': 'jam kerja',
    'water absorbency': 'daya serap air',
    'repeat the same grade': 'tinggal kelas',
    'be enrolled': 'terdaftar',
    'surface': 'permukaan',
    'sewage': 'air limbah',
    'junior high school graduate': 'lulusan SMP',
    'new graduate': 'lulusan baru',
    'muddy water': 'air berlumpur',
    'salary': 'gaji',
    'low wages': 'upah rendah',
    'old-fashioned': 'kuno',
    'old lunar calendar': 'kalender lunar lama',
    "child's mind": 'pikiran anak',
    "child's heart": 'hati anak',
    'charcoal fire': 'api arang',
    'dilute': 'mengencerkan',
    'water down': 'mengencerkan',
    'spring water': 'mata air',
  };
}
