import 'curriculum_models.dart';

class CourseTerm {
  const CourseTerm(this.word, this.romaji, this.meaning);
  final String word;
  final String romaji;
  final String meaning;
}

class CourseExample {
  const CourseExample(this.japanese, this.romaji, this.meaning, this.use);
  final String japanese;
  final String romaji;
  final String meaning;
  final String use;
}

class CourseSubchapter {
  const CourseSubchapter({required this.number, required this.title, required this.body, required this.examples});
  final String number;
  final String title;
  final String body;
  final List<CourseExample> examples;
}

class CourseChapter {
  const CourseChapter({required this.title, required this.summary, required this.grammar, required this.terms, required this.examples, required this.subchapters, required this.imageUrl, required this.imageLabel});
  final String title;
  final String summary;
  final List<String> grammar;
  final List<CourseTerm> terms;
  final List<CourseExample> examples;
  final List<CourseSubchapter> subchapters;
  final String imageUrl;
  final String imageLabel;
}

class N5N4CourseContent {
  const N5N4CourseContent._();

  static const n5Image = 'https://www.irodori.jpf.go.jp/en/illust/starter.html';
  static const n4Image = 'https://www.irodori.jpf.go.jp/illust/elementary01.html';
  static const kanaImage = 'https://www.tofugu.com/japanese/hiragana-chart/';

  static CourseChapter? forUnit(String level, CurriculumUnit unit) {
    final list = level == 'N5' ? n5 : level == 'N4' ? n4 : const <CourseChapter>[];
    final index = unit.sequence - 1;
    if (index < 0 || index >= list.length) return null;
    return list[index];
  }

  static const List<CourseChapter> n5 = [
    CourseChapter(
      title: 'Perkenalan & Identitas',
      summary: 'Membangun fondasi untuk menyapa, memperkenalkan nama, pekerjaan, asal, dan menanyakan identitas.',
      grammar: ['A は B です', 'A は B じゃありません', 'A は B ですか', 'N も', 'N1 の N2'],
      terms: [
        CourseTerm('私','watashi','saya'), CourseTerm('名前','namae','nama'), CourseTerm('人','hito','orang'), CourseTerm('学生','gakusei','pelajar'), CourseTerm('先生','sensei','guru'), CourseTerm('会社員','kaishain','karyawan perusahaan'), CourseTerm('医者','isha','dokter'), CourseTerm('研究者','kenkyuusha','peneliti'), CourseTerm('日本','Nihon','Jepang'), CourseTerm('インドネシア','Indoneshia','Indonesia'), CourseTerm('国','kuni','negara'), CourseTerm('友だち','tomodachi','teman'),
      ],
      examples: [
        CourseExample('はじめまして。','Hajimemashite.','Salam kenal.','Dipakai saat pertama kali bertemu.'),
        CourseExample('わたしは アニです。','Watashi wa Ani desu.','Saya Ani.','Pengenalan nama dengan pola は〜です.'),
        CourseExample('アニさんは 学生ですか。','Ani-san wa gakusei desu ka.','Apakah Ani seorang pelajar?','Pertanyaan identitas sederhana.'),
        CourseExample('わたしも 学生です。','Watashi mo gakusei desu.','Saya juga pelajar.','も menggantikan は untuk makna “juga”.'),
      ],
      subchapters: [
        CourseSubchapter(number:'1.1', title:'Salam & nama', body:'Fokus pada ungkapan pembuka, nama, dan respon sopan.', examples:[CourseExample('おはようございます。','Ohayou gozaimasu.','Selamat pagi.','Dipakai pada pagi hari dalam situasi sopan.'), CourseExample('わたしは リナです。','Watashi wa Rina desu.','Saya Rina.','Pola dasar memperkenalkan diri.')]),
        CourseSubchapter(number:'1.2', title:'Pekerjaan & status', body:'Pelajari sebutan pelajar, guru, karyawan, dokter, dan profesi dasar.', examples:[CourseExample('わたしは 学生です。','Watashi wa gakusei desu.','Saya pelajar.','Menyatakan status.'), CourseExample('田中さんは 先生です。','Tanaka-san wa sensei desu.','Tanaka adalah guru.','Mengidentifikasi profesi orang lain.')]),
        CourseSubchapter(number:'1.3', title:'Negara & kebangsaan', body:'Gunakan 国 dan bentuk kebangsaan untuk memperkenalkan asal.', examples:[CourseExample('インドネシアじんです。','Indoneshia-jin desu.','Saya orang Indonesia.','〜人 menunjukkan kebangsaan/orang dari negara tertentu.'), CourseExample('日本の 学生です。','Nihon no gakusei desu.','Pelajar Jepang.','の menghubungkan kata benda.')]),
        CourseSubchapter(number:'1.4', title:'Tanya jawab identitas', body:'Berlatih bertanya dan menjawab menggunakan ですか dan も.', examples:[CourseExample('お名前は？','Onamae wa?','Namanya?','Bentuk singkat dalam percakapan sopan.'), CourseExample('わたしも リナです。','Watashi mo Rina desu.','Saya juga Rina.','も untuk “juga”.')]),
        CourseSubchapter(number:'1.5', title:'Produksi & review', body:'Buat perkenalan 3–4 kalimat dari nama, negara, dan status.', examples:[CourseExample('はじめまして。わたしは アリです。','Hajimemashite. Watashi wa Ari desu.','Salam kenal. Saya Ari.','Contoh pembukaan perkenalan.'), CourseExample('インドネシアじんです。どうぞよろしく おねがいします。','Indoneshia-jin desu. Douzo yoroshiku onegaishimasu.','Saya orang Indonesia. Mohon kerja samanya.','Penutup perkenalan formal.')]),
      ],
      imageUrl: n5Image, imageLabel: 'Irodori Starter — salam, kelas, dan situasi pemula',
    ),
    CourseChapter(
      title:'Hiragana & Dasar Membaca', summary:'Menguasai gojuuon, dakuten, handakuten, kombinasi kecil, dan membaca kata sederhana.',
      grammar:['Vokal あいうえお','Baris か〜わ','が/ざ/だ/ば/ぱ','きゃ/きゅ/きょ','っ untuk konsonan ganda'],
      terms:[CourseTerm('ひらがな','hiragana','hiragana'),CourseTerm('文字','moji','huruf/karakter'),CourseTerm('読む','yomu','membaca'),CourseTerm('書く','kaku','menulis'),CourseTerm('名前','namae','nama'),CourseTerm('日本語','nihongo','bahasa Jepang'),CourseTerm('これ','kore','ini'),CourseTerm('それ','sore','itu'),CourseTerm('あれ','are','itu di sana'),CourseTerm('ここ','koko','di sini'),CourseTerm('そこ','soko','di situ'),CourseTerm('どこ','doko','di mana')],
      examples:[CourseExample('これは 日本語です。','Kore wa Nihongo desu.','Ini bahasa Jepang.','Mengidentifikasi materi/bahasa.'),CourseExample('なまえを 書きます。','Namae o kakimasu.','Saya menulis nama.','Objek langsung dengan を.'),CourseExample('ここを 読んでください。','Koko o yonde kudasai.','Tolong baca bagian ini.','Permintaan dasar.')],
      subchapters:[CourseSubchapter(number:'2.1',title:'Vokal & gojuuon',body:'Kenali urutan bunyi dan hubungan kana dengan suara.',examples:[CourseExample('あさ','Asa','pagi','あさ dibaca a-sa, bukan a-sha.'),CourseExample('いえ','Ie','rumah','Dua vokal dibaca berurutan.')]),CourseSubchapter(number:'2.2',title:'Dakuten & handakuten',body:'Bedakan か/が, は/ば/ぱ dan perubahan bunyinya.',examples:[CourseExample('がくせい','Gakusei','pelajar','が berbunyi ga.'),CourseExample('ぱん','Pan','roti','ぱ berbunyi pa.')]),CourseSubchapter(number:'2.3',title:'Yoon & っ',body:'Latih きゃ, しゅ, ちょ serta konsonan ganda dengan っ.',examples:[CourseExample('きょう','Kyou','hari ini','きょ adalah bunyi gabungan.'),CourseExample('きって','Kitte','perangko','っ menggandakan konsonan t.')]),CourseSubchapter(number:'2.4',title:'Membaca kata',body:'Gabungkan kana menjadi kata yang memiliki arti.',examples:[CourseExample('たべる','Taberu','makan','Kata kerja dasar.'),CourseExample('のみます','Nomimasu','minum','Bentuk sopan ます.')]),CourseSubchapter(number:'2.5',title:'Latihan baca cepat',body:'Baca kalimat pendek tanpa menerjemahkan setiap huruf satu per satu.',examples:[CourseExample('わたしは アニです。','Watashi wa Ani desu.','Saya Ani.','Baca sebagai satu pola utuh.'),CourseExample('これは ほんです。','Kore wa hon desu.','Ini buku.','Latihan kelancaran membaca.')])], imageUrl:kanaImage,imageLabel:'Referensi chart Hiragana untuk latihan visual kana',
    ),
    CourseChapter(
      title:'Katakana & Kata Serapan', summary:'Mengenali katakana untuk nama, makanan, tempat, teknologi, dan kata serapan sehari-hari.',
      grammar:['ウ/オ panjang','ー untuk vokal panjang','ッ pada kata serapan','ティ/ディ/ファ/フィ/フェ/フォ'],
      terms:[CourseTerm('カタカナ','katakana','katakana'),CourseTerm('テレビ','terebi','televisi'),CourseTerm('スマホ','sumaho','smartphone'),CourseTerm('コンビニ','konbini','minimarket'),CourseTerm('ホテル','hoteru','hotel'),CourseTerm('レストラン','resutoran','restoran'),CourseTerm('コーヒー','koohii','kopi'),CourseTerm('パン','pan','roti'),CourseTerm('バス','basu','bus'),CourseTerm('タクシー','takushii','taksi'),CourseTerm('ニュース','nyuusu','berita'),CourseTerm('スポーツ','supootsu','olahraga')],
      examples:[CourseExample('コーヒーを ください。','Koohii o kudasai.','Tolong kopi.','Pesanan sederhana.'),CourseExample('ホテルは どこですか。','Hoteru wa doko desu ka.','Hotelnya di mana?','Bertanya lokasi.'),CourseExample('スマホを つかいます。','Sumaho o tsukaimasu.','Saya menggunakan smartphone.','Kosakata teknologi.')],
      subchapters:[CourseSubchapter(number:'3.1',title:'Mengenal katakana',body:'Pahami bentuk dan fungsi katakana sebagai sistem tulisan utama kata serapan.',examples:[CourseExample('テレビ','Terebi','televisi','Kata serapan dari television.'),CourseExample('ホテル','Hoteru','hotel','Kosakata umum.')]),CourseSubchapter(number:'3.2',title:'Vokal panjang',body:'Perhatikan ー karena panjang bunyi mengubah pengucapan.',examples:[CourseExample('コーヒー','Koohii','kopi','Ada vokal panjang.'),CourseExample('ケーキ','Keeki','kue','ケー dibaca panjang.')]),CourseSubchapter(number:'3.3',title:'Kata serapan sehari-hari',body:'Bangun kosakata untuk tempat, makanan, kendaraan, dan teknologi.',examples:[CourseExample('コンビニへ 行きます。','Konbini e ikimasu.','Saya pergi ke minimarket.','Tujuan dengan へ.'),CourseExample('バスで 行きます。','Basu de ikimasu.','Saya pergi naik bus.','Alat transportasi dengan で.')]),CourseSubchapter(number:'3.4',title:'Ejaan bunyi khusus',body:'Kenali kombinasi kecil yang tidak ada persis di gojuuon dasar.',examples:[CourseExample('ファイル','Fairu','file','ファ membentuk fa.'),CourseExample('テレビゲーム','Terebi geemu','video game','Kata majemuk serapan.')]),CourseSubchapter(number:'3.5',title:'Review membaca',body:'Baca kombinasi hiragana + katakana dalam konteks.',examples:[CourseExample('日本のホテルです。','Nihon no hoteru desu.','Ini hotel Jepang.','Campuran kanji dan katakana.'),CourseExample('コーヒーをのみます。','Koohii o nomimasu.','Saya minum kopi.','Latihan membaca kalimat.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — ilustrasi benda dan situasi kehidupan sehari-hari',
    ),
    CourseChapter(
      title:'Angka, Waktu & Tanggal', summary:'Menguasai angka, jam, hari, tanggal, frekuensi, durasi, dan jadwal sederhana.',
      grammar:['数字 + counter','N時に V','Nから Nまで','毎日/毎週/よく','いつ/何時/何分'],
      terms:[CourseTerm('一','ichi','satu'),CourseTerm('二','ni','dua'),CourseTerm('三','san','tiga'),CourseTerm('四','yon','empat'),CourseTerm('五','go','lima'),CourseTerm('六','roku','enam'),CourseTerm('七','nana','tujuh'),CourseTerm('八','hachi','delapan'),CourseTerm('九','kyuu','sembilan'),CourseTerm('十','juu','sepuluh'),CourseTerm('時','ji','jam'),CourseTerm('分','fun','menit')],
      examples:[CourseExample('七時に 起きます。','Shichi-ji ni okimasu.','Saya bangun jam tujuh.','Waktu kegiatan memakai に.'),CourseExample('九時から 五時まで はたらきます。','Ku-ji kara go-ji made hatarakimasu.','Saya bekerja dari jam 9 sampai jam 5.','Rentang waktu.'),CourseExample('今日は 月曜日です。','Kyou wa getsuyoubi desu.','Hari ini Senin.','Hari dalam minggu.')],
      subchapters:[CourseSubchapter(number:'4.1',title:'Angka dasar',body:'Hafalkan 1–100 dan pola angka majemuk.',examples:[CourseExample('十円です。','Juu-en desu.','Sepuluh yen.','Angka + counter uang.'),CourseExample('二十歳です。','Hatachi desu.','Usia saya 20 tahun.','Bentuk khusus usia 20.')]),CourseSubchapter(number:'4.2',title:'Jam & menit',body:'Pelajari variasi baca jam dan menit yang sering dipakai.',examples:[CourseExample('今、三時です。','Ima, san-ji desu.','Sekarang jam tiga.','Menyatakan waktu sekarang.'),CourseExample('五分まってください。','Go-fun matte kudasai.','Tolong tunggu lima menit.','Durasi singkat.')]),CourseSubchapter(number:'4.3',title:'Hari & tanggal',body:'Gunakan nama hari, bulan, dan tanggal untuk jadwal.',examples:[CourseExample('土曜日に 休みます。','Doyoubi ni yasumimasu.','Saya libur hari Sabtu.','Hari + に.'),CourseExample('八月に 日本へ 行きます。','Hachigatsu ni Nihon e ikimasu.','Saya pergi ke Jepang pada Agustus.','Bulan + に.')]),CourseSubchapter(number:'4.4',title:'Jadwal',body:'Gabungkan waktu mulai, selesai, dan kebiasaan.',examples:[CourseExample('九時から 勉強します。','Ku-ji kara benkyou shimasu.','Saya belajar mulai jam sembilan.','から menunjukkan awal.'),CourseExample('毎日 一時間 勉強します。','Mainichi ichi-jikan benkyou shimasu.','Saya belajar satu jam setiap hari.','Frekuensi + durasi.')]),CourseSubchapter(number:'4.5',title:'Review waktu',body:'Buat jadwal satu hari lengkap.',examples:[CourseExample('七時に 起きて、八時に 学校へ 行きます。','Shichi-ji ni okite, hachi-ji ni gakkou e ikimasu.','Bangun jam tujuh lalu pergi sekolah jam delapan.','Mengurutkan jadwal.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — ilustrasi waktu, kelas, dan kegiatan harian',
    ),
    CourseChapter(
      title:'Keluarga & Orang', summary:'Membicarakan anggota keluarga, hubungan, usia, serta mendeskripsikan orang dekat.',
      grammar:['N の N','～さん/～ちゃん/～くん','～人','いる/いない pengantar'],
      terms:[CourseTerm('家族','kazoku','keluarga'),CourseTerm('父','chichi','ayah saya'),CourseTerm('母','haha','ibu saya'),CourseTerm('兄','ani','kakak laki-laki saya'),CourseTerm('姉','ane','kakak perempuan saya'),CourseTerm('弟','otouto','adik laki-laki'),CourseTerm('妹','imouto','adik perempuan'),CourseTerm('夫','otto','suami'),CourseTerm('妻','tsuma','istri'),CourseTerm('子ども','kodomo','anak'),CourseTerm('男の人','otoko no hito','pria'),CourseTerm('女の人','onna no hito','wanita')],
      examples:[CourseExample('これは わたしの 母です。','Kore wa watashi no haha desu.','Ini ibu saya.','N の N untuk hubungan/possession.'),CourseExample('家族は 五人です。','Kazoku wa go-nin desu.','Keluarga saya lima orang.','Counter orang.'),CourseExample('兄は 会社員です。','Ani wa kaishain desu.','Kakak laki-laki saya karyawan.','Deskripsi anggota keluarga.')],
      subchapters:[CourseSubchapter(number:'5.1',title:'Anggota inti',body:'Bedakan istilah saat menyebut keluarga sendiri dan keluarga orang lain.',examples:[CourseExample('父は 会社員です。','Chichi wa kaishain desu.','Ayah saya karyawan.','Istilah keluarga sendiri.'),CourseExample('田中さんの お父さんです。','Tanaka-san no otousan desu.','Itu ayah Tn. Tanaka.','Panggilan sopan untuk keluarga orang lain.')]),CourseSubchapter(number:'5.2',title:'Usia & jumlah orang',body:'Latih angka untuk usia dan counter ～人.',examples:[CourseExample('妹は 十八歳です。','Imouto wa juu-hassai desu.','Adik perempuan saya berusia 18 tahun.','Menyatakan usia.'),CourseExample('家族は 四人です。','Kazoku wa yo-nin desu.','Keluarga saya empat orang.','Jumlah anggota.')]),CourseSubchapter(number:'5.3',title:'Hubungan & kepemilikan',body:'Gunakan の untuk menjelaskan hubungan dua nomina.',examples:[CourseExample('山田さんは 友だちの 先生です。','Yamada-san wa tomodachi no sensei desu.','Yamada adalah guru teman saya.','N の N.'),CourseExample('これは 母の かばんです。','Kore wa haha no kaban desu.','Ini tas ibu saya.','Pemilik benda.')]),CourseSubchapter(number:'5.4',title:'Mendeskripsikan orang',body:'Gabungkan profesi, usia, dan hubungan.',examples:[CourseExample('弟は 学生です。','Otouto wa gakusei desu.','Adik laki-laki saya pelajar.','Identitas sederhana.'),CourseExample('妹は 元気です。','Imouto wa genki desu.','Adik perempuan saya sehat/bersemangat.','Deskripsi sifat.')]),CourseSubchapter(number:'5.5',title:'Review keluarga',body:'Buat diagram keluarga lalu jelaskan dengan kalimat pendek.',examples:[CourseExample('わたしの 家族は 四人です。','Watashi no kazoku wa yo-nin desu.','Keluarga saya empat orang.','Pembukaan deskripsi.'),CourseExample('父と 母と 兄と わたしです。','Chichi to haha to ani to watashi desu.','Ayah, ibu, kakak laki-laki, dan saya.','Menggabungkan daftar orang.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — ilustrasi keluarga dan orang sekitar',
    ),
    CourseChapter(
      title:'Benda & Kepemilikan', summary:'Menunjuk benda, menanyakan apa/siapa pemiliknya, dan membuat frasa nomina.',
      grammar:['これ/それ/あれ','この/その/あの + N','だれの N','そうです/そうじゃありません'],
      terms:[CourseTerm('本','hon','buku'),CourseTerm('辞書','jisho','kamus'),CourseTerm('かばん','kaban','tas'),CourseTerm('時計','tokei','jam'),CourseTerm('傘','kasa','payung'),CourseTerm('鉛筆','enpitsu','pensil'),CourseTerm('机','tsukue','meja'),CourseTerm('椅子','isu','kursi'),CourseTerm('携帯','keitai','ponsel'),CourseTerm('財布','saifu','dompet'),CourseTerm('鍵','kagi','kunci'),CourseTerm('写真','shashin','foto')],
      examples:[CourseExample('これは わたしの 本です。','Kore wa watashi no hon desu.','Ini buku saya.','Menunjuk benda + kepemilikan.'),CourseExample('その かばんは だれのですか。','Sono kaban wa dare no desu ka.','Tas itu milik siapa?','Pertanyaan pemilik.'),CourseExample('あの 時計は 先生のです。','Ano tokei wa sensei no desu.','Jam itu milik guru.','Pemilik dapat dihilangkan setelah の.')],
      subchapters:[CourseSubchapter(number:'6.1',title:'Kore / sore / are',body:'Bedakan jarak benda dari pembicara dan lawan bicara.',examples:[CourseExample('これは 本です。','Kore wa hon desu.','Ini buku.','Dekat pembicara.'),CourseExample('それは 何ですか。','Sore wa nan desu ka.','Itu apa?','Dekat lawan bicara.')]),CourseSubchapter(number:'6.2',title:'Kono / sono / ano',body:'Kata penunjuk ini langsung diikuti kata benda.',examples:[CourseExample('この 本は おもしろいです。','Kono hon wa omoshiroi desu.','Buku ini menarik.','この + nomina.'),CourseExample('あの 店は 有名です。','Ano mise wa yuumei desu.','Toko itu terkenal.','あの + nomina.')]),CourseSubchapter(number:'6.3',title:'Kepemilikan',body:'Gunakan の untuk menyatakan pemilik atau hubungan benda.',examples:[CourseExample('日本語の 本です。','Nihongo no hon desu.','Buku bahasa Jepang.','N1 の N2.'),CourseExample('これは 先生のです。','Kore wa sensei no desu.','Ini milik guru.','Nomina kedua dapat dihilangkan.')]),CourseSubchapter(number:'6.4',title:'Tanya jawab benda',body:'Latih 何, だれ, dan jawaban そうです.',examples:[CourseExample('それは 辞書ですか。','Sore wa jisho desu ka.','Apakah itu kamus?','Pertanyaan ya/tidak.'),CourseExample('はい、そうです。','Hai, sou desu.','Ya, benar.','Konfirmasi.')]),CourseSubchapter(number:'6.5',title:'Review benda',body:'Identifikasi lima benda di sekitar secara spontan.',examples:[CourseExample('これは 机です。','Kore wa tsukue desu.','Ini meja.','Pengenalan benda.'),CourseExample('その 鍵は わたしのです。','Sono kagi wa watashi no desu.','Kunci itu milik saya.','Praktik kepemilikan.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — benda di kelas dan kehidupan sehari-hari',
    ),
    CourseChapter(
      title:'Tempat, Posisi & Keberadaan', summary:'Menanyakan lokasi dan memperkenalkan tempat dengan ここ/そこ/あそこ serta あります/います.',
      grammar:['ここ/そこ/あそこ','どこ/どちら','N は tempat です','N に N があります/います','N の 上/下/前/後ろ'],
      terms:[CourseTerm('駅','eki','stasiun'),CourseTerm('学校','gakkou','sekolah'),CourseTerm('会社','kaisha','perusahaan/kantor'),CourseTerm('銀行','ginkou','bank'),CourseTerm('病院','byouin','rumah sakit'),CourseTerm('店','mise','toko'),CourseTerm('家','ie','rumah'),CourseTerm('部屋','heya','kamar'),CourseTerm('上','ue','atas'),CourseTerm('下','shita','bawah'),CourseTerm('前','mae','depan'),CourseTerm('後ろ','ushiro','belakang')],
      examples:[CourseExample('駅は どこですか。','Eki wa doko desu ka.','Stasiun di mana?','Pertanyaan lokasi.'),CourseExample('教室に 先生が います。','Kyoushitsu ni sensei ga imasu.','Ada guru di kelas.','Orang memakai います.'),CourseExample('机の 上に 本が あります。','Tsukue no ue ni hon ga arimasu.','Ada buku di atas meja.','Benda memakai あります.')],
      subchapters:[CourseSubchapter(number:'7.1',title:'Koko / soko / asoko',body:'Gunakan kata tempat sesuai jarak.',examples:[CourseExample('トイレは そこです。','Toire wa soko desu.','Toiletnya di situ.','Menunjukkan lokasi.'),CourseExample('駅は あそこです。','Eki wa asoko desu.','Stasiun ada di sana.','Lokasi jauh dari keduanya.')]),CourseSubchapter(number:'7.2',title:'Arimasu & imasu',body:'Bedakan benda/tanaman dengan manusia/hewan.',examples:[CourseExample('机が あります。','Tsukue ga arimasu.','Ada meja.','Benda mati.'),CourseExample('猫が います。','Neko ga imasu.','Ada kucing.','Makhluk hidup.')]),CourseSubchapter(number:'7.3',title:'Posisi',body:'Pelajari 上, 下, 前, 後ろ, 中, 右, 左.',examples:[CourseExample('本は 机の 上です。','Hon wa tsukue no ue desu.','Buku di atas meja.','Posisi relatif.'),CourseExample('銀行は 駅の 前です。','Ginkou wa eki no mae desu.','Bank di depan stasiun.','Lokasi berdasarkan landmark.')]),CourseSubchapter(number:'7.4',title:'Tempat umum',body:'Bangun kosakata lokasi yang sering muncul dalam listening.',examples:[CourseExample('病院は どこですか。','Byouin wa doko desu ka.','Rumah sakit di mana?','Konteks umum.'),CourseExample('会社は 駅の 近くです。','Kaisha wa eki no chikaku desu.','Kantor dekat stasiun.','近く = dekat.')]),CourseSubchapter(number:'7.5',title:'Review lokasi',body:'Buat peta mini lingkungan lalu jelaskan tiga lokasi.',examples:[CourseExample('コンビニは 駅の となりです。','Konbini wa eki no tonari desu.','Minimarket di sebelah stasiun.','Posisi relatif.'),CourseExample('学校は ここです。','Gakkou wa koko desu.','Sekolah ada di sini.','Menunjuk lokasi.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — ilustrasi tempat dan arah di kehidupan sehari-hari',
    ),
    CourseChapter(
      title:'Pergi, Datang & Transportasi', summary:'Menyatakan tujuan, asal perjalanan, kendaraan, teman perjalanan, dan waktu bepergian.',
      grammar:['N へ/に 行きます','N から 来ます','N で 行きます','N と 行きます','いつ'],
      terms:[CourseTerm('行く','iku','pergi'),CourseTerm('来る','kuru','datang'),CourseTerm('帰る','kaeru','pulang'),CourseTerm('電車','densha','kereta'),CourseTerm('新幹線','shinkansen','shinkansen'),CourseTerm('車','kuruma','mobil'),CourseTerm('自転車','jitensha','sepeda'),CourseTerm('飛行機','hikouki','pesawat'),CourseTerm('駅','eki','stasiun'),CourseTerm('空港','kuukou','bandara') ,CourseTerm('旅行','ryokou','perjalanan'),CourseTerm('友だち','tomodachi','teman')],
      examples:[CourseExample('学校へ 行きます。','Gakkou e ikimasu.','Saya pergi ke sekolah.','Tujuan dengan へ.'),CourseExample('バスで 会社へ 行きます。','Basu de kaisha e ikimasu.','Saya pergi ke kantor naik bus.','Kendaraan dengan で.'),CourseExample('友だちと 日本へ 行きます。','Tomodachi to Nihon e ikimasu.','Saya pergi ke Jepang bersama teman.','Teman perjalanan dengan と.')],
      subchapters:[CourseSubchapter(number:'8.1',title:'Tujuan perjalanan',body:'Latih に dan へ untuk tujuan.',examples:[CourseExample('駅に 行きます。','Eki ni ikimasu.','Saya pergi ke stasiun.','に menunjukkan tujuan.'),CourseExample('うちへ 帰ります。','Uchi e kaerimasu.','Saya pulang ke rumah.','へ menunjukkan arah/tujuan.')]),CourseSubchapter(number:'8.2',title:'Kendaraan',body:'Gunakan で untuk alat/cara melakukan perjalanan.',examples:[CourseExample('電車で 行きます。','Densha de ikimasu.','Saya pergi naik kereta.','Transportasi.'),CourseExample('自転車で 学校へ 行きます。','Jitensha de gakkou e ikimasu.','Saya pergi ke sekolah naik sepeda.','Gabungan kendaraan + tujuan.')]),CourseSubchapter(number:'8.3',title:'Dengan siapa',body:'Gunakan と untuk teman/pendamping.',examples:[CourseExample('友だちと 行きます。','Tomodachi to ikimasu.','Saya pergi bersama teman.','Pendamping.'),CourseExample('一人で 行きます。','Hitori de ikimasu.','Saya pergi sendirian.','一人で = sendirian.')]),CourseSubchapter(number:'8.4',title:'Kapan bepergian',body:'Tanya いつ dan gabungkan dengan waktu.',examples:[CourseExample('いつ 日本へ 行きますか。','Itsu Nihon e ikimasu ka.','Kapan pergi ke Jepang?','Pertanyaan waktu.'),CourseExample('来週 行きます。','Raishuu ikimasu.','Saya pergi minggu depan.','Jawaban waktu tanpa に pada beberapa ekspresi.')]),CourseSubchapter(number:'8.5',title:'Review transportasi',body:'Buat percakapan perjalanan dua orang.',examples:[CourseExample('どこへ 行きますか。','Doko e ikimasu ka.','Mau pergi ke mana?','Membuka percakapan.'),CourseExample('空港へ 行きます。飛行機で 行きます。','Kuukou e ikimasu. Hikouki de ikimasu.','Ke bandara. Naik pesawat.','Dua informasi perjalanan.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — transportasi, perjalanan, dan tempat umum',
    ),
    CourseChapter(
      title:'Rutinitas & Aktivitas', summary:'Menyusun rutinitas dengan verba bentuk ます, objek を, tempat で, ajakan dan urutan kegiatan.',
      grammar:['N を Vます','Place で Vます','Vませんか','Vましょう','Vて、V'],
      terms:[CourseTerm('起きる','okiru','bangun'),CourseTerm('寝る','neru','tidur'),CourseTerm('食べる','taberu','makan'),CourseTerm('飲む','nomu','minum'),CourseTerm('見る','miru','melihat/menonton'),CourseTerm('聞く','kiku','mendengar'),CourseTerm('読む','yomu','membaca'),CourseTerm('書く','kaku','menulis'),CourseTerm('勉強する','benkyou suru','belajar'),CourseTerm('働く','hataraku','bekerja'),CourseTerm('休む','yasumu','istirahat/libur'),CourseTerm('買う','kau','membeli')],
      examples:[CourseExample('朝ごはんを 食べます。','Asagohan o tabemasu.','Saya sarapan.','Objek dengan を.'),CourseExample('図書館で 本を 読みます。','Toshokan de hon o yomimasu.','Saya membaca buku di perpustakaan.','Tempat kegiatan dengan で.'),CourseExample('いっしょに 映画を 見ませんか。','Issho ni eiga o mimasen ka.','Mau menonton film bersama?','Ajakan halus.')],
      subchapters:[CourseSubchapter(number:'9.1',title:'Verba bentuk ます',body:'Bangun fondasi kosakata aksi sehari-hari.',examples:[CourseExample('毎朝 六時に 起きます。','Maiasa roku-ji ni okimasu.','Setiap pagi bangun jam enam.','Rutinitas.'),CourseExample('十一時に 寝ます。','Juuichi-ji ni nemasu.','Saya tidur jam sebelas.','Kegiatan malam.')]),CourseSubchapter(number:'9.2',title:'Objek を',body:'Tentukan benda yang dikenai tindakan.',examples:[CourseExample('日本語を 勉強します。','Nihongo o benkyou shimasu.','Saya belajar bahasa Jepang.','Belajar sesuatu.'),CourseExample('音楽を 聞きます。','Ongaku o kikimasu.','Saya mendengarkan musik.','Mendengar sesuatu.')]),CourseSubchapter(number:'9.3',title:'Tempat で',body:'Bedakan で kegiatan dengan に tujuan/keberadaan.',examples:[CourseExample('家で 勉強します。','Ie de benkyou shimasu.','Saya belajar di rumah.','Lokasi aktivitas.'),CourseExample('学校で 日本語を 話します。','Gakkou de Nihongo o hanashimasu.','Saya berbicara bahasa Jepang di sekolah.','Kegiatan di tempat.')]),CourseSubchapter(number:'9.4',title:'Ajakan',body:'Gunakan ませんか dan ましょう untuk mengundang atau mengajak.',examples:[CourseExample('コーヒーを 飲みませんか。','Koohii o nomimasen ka.','Mau minum kopi?','Ajakan.'),CourseExample('休みましょう。','Yasumimashou.','Mari istirahat.','Ajakan langsung.')]),CourseSubchapter(number:'9.5',title:'Urutan kegiatan',body:'Hubungkan dua aktivitas sederhana dengan て.',examples:[CourseExample('朝ごはんを 食べて、学校へ 行きます。','Asagohan o tabete, gakkou e ikimasu.','Sarapan lalu pergi ke sekolah.','Urutan kegiatan.'),CourseExample('本を 読んで、寝ます。','Hon o yonde, nemasu.','Membaca buku lalu tidur.','Menghubungkan aksi.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — aktivitas harian dan belajar di kelas',
    ),
    CourseChapter(
      title:'Makanan & Belanja', summary:'Memesan, bertanya harga, menyebut makanan/minuman, jumlah, dan ungkapan pelayanan dasar.',
      grammar:['N を ください','N を おねがいします','いくらですか','N が ほしいです pengantar','Counter benda pengantar'],
      terms:[CourseTerm('食べ物','tabemono','makanan'),CourseTerm('飲み物','nomimono','minuman'),CourseTerm('ご飯','gohan','nasi/makanan'),CourseTerm('水','mizu','air'),CourseTerm('お茶','ocha','teh'),CourseTerm('コーヒー','koohii','kopi'),CourseTerm('パン','pan','roti'),CourseTerm('肉','niku','daging'),CourseTerm('魚','sakana','ikan'),CourseTerm('野菜','yasai','sayuran'),CourseTerm('果物','kudamono','buah'),CourseTerm('値段','nedan','harga')],
      examples:[CourseExample('これを ください。','Kore o kudasai.','Tolong yang ini.','Permintaan saat membeli.'),CourseExample('この パンは いくらですか。','Kono pan wa ikura desu ka.','Roti ini berapa harganya?','Menanyakan harga.'),CourseExample('水を おねがいします。','Mizu o onegaishimasu.','Air, tolong.','Permintaan sopan.')],
      subchapters:[CourseSubchapter(number:'10.1',title:'Nama makanan',body:'Bangun kosakata menu dan bahan makanan umum.',examples:[CourseExample('魚を 食べます。','Sakana o tabemasu.','Saya makan ikan.','Objek makanan.'),CourseExample('野菜が 好きです。','Yasai ga suki desu.','Saya suka sayuran.','Pengantar pola suka.')]),CourseSubchapter(number:'10.2',title:'Memesan',body:'Gunakan ください dan おねがいします.',examples:[CourseExample('コーヒーを 一つ ください。','Koohii o hitotsu kudasai.','Tolong satu kopi.','Pesanan + jumlah.'),CourseExample('これを おねがいします。','Kore o onegaishimasu.','Yang ini, tolong.','Permintaan sopan.')]),CourseSubchapter(number:'10.3',title:'Harga',body:'Latih angka + 円 dan pertanyaan いくら.',examples:[CourseExample('これは 千円です。','Kore wa sen-en desu.','Ini seribu yen.','Harga.'),CourseExample('いくらですか。','Ikura desu ka.','Berapa harganya?','Pertanyaan harga.')]),CourseSubchapter(number:'10.4',title:'Di restoran',body:'Gabungkan salam, pesanan, dan ucapan setelah makan.',examples:[CourseExample('ラーメンを おねがいします。','Raamen o onegaishimasu.','Ramen, tolong.','Memesan.'),CourseExample('ごちそうさまでした。','Gochisousama deshita.','Terima kasih atas makanannya.','Ucapan setelah makan.')]),CourseSubchapter(number:'10.5',title:'Review belanja',body:'Lakukan role-play pembeli dan penjual.',examples:[CourseExample('りんごを 三つ ください。','Ringo o mittsu kudasai.','Tolong tiga apel.','Jumlah benda.'),CourseExample('はい、全部で 六百円です。','Hai, zenbu de roppyaku-en desu.','Ya, totalnya 600 yen.','Total harga sederhana.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — makanan dan situasi sehari-hari',
    ),
    CourseChapter(
      title:'Deskripsi & Adjektiva', summary:'Mendeskripsikan orang, benda, kota, makanan, dan suasana dengan i-adjective/na-adjective.',
      grammar:['い-adjective + です','な-adjective + です','Adj じゃないです','Adj + N','どうですか/どんな N'],
      terms:[CourseTerm('大きい','ookii','besar'),CourseTerm('小さい','chiisai','kecil'),CourseTerm('新しい','atarashii','baru'),CourseTerm('古い','furui','lama'),CourseTerm('高い','takai','mahal/tinggi'),CourseTerm('安い','yasui','murah'),CourseTerm('暑い','atsui','panas'),CourseTerm('寒い','samui','dingin'),CourseTerm('おいしい','oishii','enak'),CourseTerm('おもしろい','omoshiroi','menarik'),CourseTerm('静か','shizuka','tenang'),CourseTerm('きれい','kirei','indah/bersih')],
      examples:[CourseExample('この 本は おもしろいです。','Kono hon wa omoshiroi desu.','Buku ini menarik.','i-adjective.'),CourseExample('この 町は 静かです。','Kono machi wa shizuka desu.','Kota ini tenang.','na-adjective.'),CourseExample('この レストランは 高くないです。','Kono resutoran wa takakunai desu.','Restoran ini tidak mahal.','Negatif i-adjective.')],
      subchapters:[CourseSubchapter(number:'11.1',title:'i-adjective',body:'Kenali ciri adjective yang berakhir い dan perubahan negatif dasarnya.',examples:[CourseExample('大きい かばんです。','Ookii kaban desu.','Tas besar.','Adj + noun.'),CourseExample('この りんごは 甘くないです。','Kono ringo wa amakunai desu.','Apel ini tidak manis.','Negatif.')]),CourseSubchapter(number:'11.2',title:'na-adjective',body:'Gunakan です setelah kata seperti 静か, 便利, 元気.',examples:[CourseExample('この 部屋は きれいです。','Kono heya wa kirei desu.','Kamar ini bersih.','na-adjective.'),CourseExample('町は 静かじゃないです。','Machi wa shizuka janai desu.','Kotanya tidak tenang.','Negatif.')]),CourseSubchapter(number:'11.3',title:'Mendeskripsikan benda',body:'Gabungkan penunjuk + adjective + benda.',examples:[CourseExample('その 大きい 車です。','Sono ookii kuruma desu.','Mobil besar itu.','Frasa nomina.'),CourseExample('新しい 時計です。','Atarashii tokei desu.','Jam baru.','Deskripsi benda.')]),CourseSubchapter(number:'11.4',title:'Bagaimana?',body:'Gunakan どうですか dan どんな untuk meminta deskripsi.',examples:[CourseExample('日本の 食べ物は どうですか。','Nihon no tabemono wa dou desu ka.','Bagaimana makanan Jepang?','Meminta opini/deskripsi.'),CourseExample('どんな 町ですか。','Donna machi desu ka.','Kota seperti apa?','Menanyakan karakter.')]),CourseSubchapter(number:'11.5',title:'Review adjective',body:'Deskripsikan satu tempat, satu benda, dan satu makanan.',examples:[CourseExample('この 店は 安くて きれいです。','Kono mise wa yasukute kirei desu.','Toko ini murah dan bersih.','Penghubung adjective.'),CourseExample('日本料理は おいしいです。','Nihon ryouri wa oishii desu.','Masakan Jepang enak.','Deskripsi makanan.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — gambar tempat, benda, makanan, dan aktivitas',
    ),
    CourseChapter(
      title:'Suka, Tidak Suka & Kemampuan', summary:'Menyatakan preferensi, keterampilan, pemahaman dasar, dan alasan sederhana.',
      grammar:['N が 好きです','N が 嫌いです','N が 上手/下手です','N が 分かります','～から'],
      terms:[CourseTerm('好き','suki','suka'),CourseTerm('嫌い','kirai','tidak suka'),CourseTerm('上手','jouzu','pandai'),CourseTerm('下手','heta','kurang pandai'),CourseTerm('分かる','wakaru','mengerti'),CourseTerm('音楽','ongaku','musik'),CourseTerm('映画','eiga','film'),CourseTerm('スポーツ','supootsu','olahraga'),CourseTerm('料理','ryouri','masakan/memasak'),CourseTerm('日本語','nihongo','bahasa Jepang')],
      examples:[CourseExample('日本語が 好きです。','Nihongo ga suki desu.','Saya suka bahasa Jepang.','Preferensi.'),CourseExample('料理が 上手です。','Ryouri ga jouzu desu.','Pandai memasak.','Kemampuan yang dinilai.'),CourseExample('少し 日本語が 分かります。','Sukoshi Nihongo ga wakarimasu.','Saya sedikit mengerti bahasa Jepang.','Pemahaman.')],
      subchapters:[CourseSubchapter(number:'12.1',title:'Suka & tidak suka',body:'Gunakan が, bukan を, pada pola 好き/嫌い.',examples:[CourseExample('音楽が 好きです。','Ongaku ga suki desu.','Saya suka musik.','Pola suka.'),CourseExample('スポーツが 嫌いです。','Supootsu ga kirai desu.','Saya tidak suka olahraga.','Pola tidak suka.')]),CourseSubchapter(number:'12.2',title:'Jouzu & heta',body:'Menyatakan kemampuan secara umum.',examples:[CourseExample('日本語が 上手です。','Nihongo ga jouzu desu.','Pandai bahasa Jepang.','Kemampuan.'),CourseExample('歌が 下手です。','Uta ga heta desu.','Kurang pandai bernyanyi.','Menyatakan kelemahan.')]),CourseSubchapter(number:'12.3',title:'Wakarimasu',body:'Bedakan mengerti sesuatu dengan mampu melakukan sesuatu.',examples:[CourseExample('漢字が 少し 分かります。','Kanji ga sukoshi wakarimasu.','Saya sedikit mengerti kanji.','Pemahaman.'),CourseExample('英語が 分かりません。','Eigo ga wakarimasen.','Saya tidak mengerti bahasa Inggris.','Bentuk negatif.')]),CourseSubchapter(number:'12.4',title:'Alasan から',body:'Hubungkan alasan dengan keputusan sederhana.',examples:[CourseExample('好きですから、毎日 勉強します。','Suki desu kara, mainichi benkyou shimasu.','Karena suka, saya belajar setiap hari.','Alasan + keputusan.'),CourseExample('忙しいですから、今日は 休みます。','Isogashii desu kara, kyou wa yasumimasu.','Karena sibuk, hari ini saya libur.','Alasan.')]),CourseSubchapter(number:'12.5',title:'Review preferensi',body:'Ceritakan tiga hal yang disukai dan satu hal yang tidak.',examples:[CourseExample('映画が 好きです。','Eiga ga suki desu.','Saya suka film.','Preferensi.'),CourseExample('スポーツは あまり 好きじゃありません。','Supootsu wa amari suki ja arimasen.','Saya tidak terlalu suka olahraga.','Negatif preferensi.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — kegiatan, hobi, dan percakapan sehari-hari',
    ),
    CourseChapter(
      title:'Permintaan, Izin & Larangan', summary:'Memakai bentuk て untuk meminta bantuan, meminta izin, larangan, dan kebiasaan yang sedang berlangsung.',
      grammar:['Vてください','Vてもいいです','Vてはいけません','Vています pengantar','Vないでください pengantar'],
      terms:[CourseTerm('待つ','matsu','menunggu'),CourseTerm('見る','miru','melihat'),CourseTerm('入る','hairu','masuk'),CourseTerm('座る','suwaru','duduk'),CourseTerm('使う','tsukau','menggunakan'),CourseTerm('開ける','akeru','membuka'),CourseTerm('閉める','shimeru','menutup'),CourseTerm('話す','hanasu','berbicara'),CourseTerm('写真','shashin','foto'),CourseTerm('静かに','shizuka ni','dengan tenang')],
      examples:[CourseExample('ちょっと 待ってください。','Chotto matte kudasai.','Tolong tunggu sebentar.','Permintaan.'),CourseExample('ここに 座っても いいですか。','Koko ni suwatte mo ii desu ka.','Boleh duduk di sini?','Meminta izin.'),CourseExample('ここで 写真を 撮っては いけません。','Koko de shashin o totte wa ikemasen.','Tidak boleh mengambil foto di sini.','Larangan.')],
      subchapters:[CourseSubchapter(number:'13.1',title:'Bentuk て',body:'Bangun perubahan verba yang diperlukan untuk pola て.',examples:[CourseExample('見てください。','Mite kudasai.','Tolong lihat.','る-verba → て.'),CourseExample('読んでください。','Yonde kudasai.','Tolong baca.','む-verba → んで.')]),CourseSubchapter(number:'13.2',title:'Permintaan',body:'Pakai てください untuk instruksi sopan.',examples:[CourseExample('名前を 書いてください。','Namae o kaite kudasai.','Tolong tulis nama.','Instruksi.'),CourseExample('もう一度 言ってください。','Mou ichido itte kudasai.','Tolong katakan sekali lagi.','Listening repair.')]),CourseSubchapter(number:'13.3',title:'Izin',body:'Pakai てもいいですか untuk meminta izin.',examples:[CourseExample('ここで 食べても いいですか。','Koko de tabete mo ii desu ka.','Boleh makan di sini?','Izin.'),CourseExample('写真を 撮っても いいです。','Shashin o totte mo ii desu.','Boleh mengambil foto.','Memberi izin.')]),CourseSubchapter(number:'13.4',title:'Larangan',body:'Pakai てはいけません untuk aturan jelas.',examples:[CourseExample('ここに 入っては いけません。','Koko ni haitte wa ikemasen.','Tidak boleh masuk ke sini.','Larangan.'),CourseExample('ここで タバコを 吸っては いけません。','Koko de tabako o sutte wa ikemasen.','Dilarang merokok di sini.','Aturan tempat.')]),CourseSubchapter(number:'13.5',title:'Review aturan',body:'Bedakan permintaan, izin, dan larangan.',examples:[CourseExample('見てください。','Mite kudasai.','Tolong lihat.','Permintaan.'),CourseExample('見ても いいですか。','Mite mo ii desu ka.','Boleh lihat?','Izin.')])],imageUrl:n5Image,imageLabel:'Irodori Starter — instruksi kelas dan aturan kehidupan sehari-hari',
    ),
  ];

  static const List<CourseChapter> n4 = [
    CourseChapter(title:'Menghubungkan Kalimat & Bentuk て',summary:'Memakai bentuk て secara lebih produktif untuk urutan, keadaan, permintaan, dan kegiatan sedang berlangsung.',grammar:['Vて、V','Vています','Vてから','Vてもいい','Vてはいけない'],terms:[CourseTerm('続ける','tsuzukeru','melanjutkan'),CourseTerm('始める','hajimeru','memulai'),CourseTerm('終わる','owaru','selesai'),CourseTerm('持つ','motsu','membawa/memegang'),CourseTerm('使う','tsukau','menggunakan'),CourseTerm('作る','tsukuru','membuat'),CourseTerm('洗う','arau','mencuci'),CourseTerm('着る','kiru','memakai'),CourseTerm('住む','sumu','tinggal'),CourseTerm('働く','hataraku','bekerja')],examples:[CourseExample('朝ごはんを 食べて、会社へ 行きます。','Asagohan o tabete, kaisha e ikimasu.','Sarapan lalu pergi ke kantor.','Urutan kegiatan.'),CourseExample('今、本を 読んでいます。','Ima, hon o yonde imasu.','Sekarang sedang membaca buku.','Sedang berlangsung.'),CourseExample('仕事が 終わってから、帰ります。','Shigoto ga owatte kara, kaerimasu.','Setelah pekerjaan selesai, saya pulang.','Urutan dengan てから.')],subchapters:[CourseSubchapter(number:'1.1',title:'Urutan kegiatan',body:'Gunakan て untuk menyusun beberapa aksi.',examples:[CourseExample('顔を 洗って、朝ごはんを 食べます。','Kao o aratte, asagohan o tabemasu.','Cuci muka lalu sarapan.','Urutan natural.')]),CourseSubchapter(number:'1.2',title:'Sedang berlangsung',body:'Bedakan kebiasaan bentuk ます dengan keadaan sedang berjalan.',examples:[CourseExample('電話で 話しています。','Denwa de hanashite imasu.','Sedang berbicara lewat telepon.','Progressive.')]),CourseSubchapter(number:'1.3',title:'Setelah ...',body:'Vてから menekankan aksi kedua setelah aksi pertama selesai.',examples:[CourseExample('宿題を してから、ゲームを します。','Shukudai o shite kara, geemu o shimasu.','Setelah mengerjakan PR, saya bermain game.','Urutan.')]),CourseSubchapter(number:'1.4',title:'Izin & aturan',body:'Perkuat pola izin/larangan dalam situasi nyata.',examples:[CourseExample('ここで 使っても いいですか。','Koko de tsukatte mo ii desu ka.','Boleh menggunakan di sini?','Izin.')]),CourseSubchapter(number:'1.5',title:'Review',body:'Gabungkan empat pola dalam rutinitas.',examples:[CourseExample('今、勉強しています。','Ima, benkyou shite imasu.','Sekarang sedang belajar.','Progressive.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — ilustrasi konteks kehidupan sehari-hari'),
    CourseChapter(title:'Bentuk Biasa & Masa Lalu',summary:'Berpindah dari bentuk sopan ke bentuk biasa untuk percakapan, catatan, dan klausa.',grammar:['Vる/Vない','Vた/Vなかった','Adj普通形','Nだった/Nじゃなかった'],terms:[CourseTerm('思う','omou','berpikir'),CourseTerm('知る','shiru','mengetahui'),CourseTerm('分かる','wakaru','mengerti'),CourseTerm('住む','sumu','tinggal'),CourseTerm('行った','itta','telah pergi'),CourseTerm('見た','mita','telah melihat'),CourseTerm('食べない','tabenai','tidak makan'),CourseTerm('忙しい','isogashii','sibuk')],examples:[CourseExample('昨日、映画を 見た。','Kinou, eiga o mita.','Kemarin menonton film.','Bentuk biasa lampau.'),CourseExample('明日、学校へ 行かない。','Ashita, gakkou e ikanai.','Besok tidak pergi sekolah.','Bentuk biasa negatif.'),CourseExample('昨日は 暇だった。','Kinou wa hima datta.','Kemarin senggang.','Noun/na-adj past.')],subchapters:[CourseSubchapter(number:'2.1',title:'Present biasa',body:'Gunakan bentuk kamus dalam percakapan informal.',examples:[CourseExample('明日 行く。','Ashita iku.','Besok pergi.','Biasa.')]),CourseSubchapter(number:'2.2',title:'Negatif biasa',body:'Bentuk ない untuk menyatakan tidak melakukan.',examples:[CourseExample('今日は 行かない。','Kyou wa ikanai.','Hari ini tidak pergi.','Negatif.')]),CourseSubchapter(number:'2.3',title:'Past biasa',body:'Latih Vた dan でした/だった.',examples:[CourseExample('昨日、勉強した。','Kinou, benkyou shita.','Kemarin belajar.','Past.')]),CourseSubchapter(number:'2.4',title:'Past negatif',body:'Menyatakan sesuatu tidak terjadi di masa lalu.',examples:[CourseExample('昨日は 忙しくなかった。','Kinou wa isogashikunakatta.','Kemarin tidak sibuk.','i-adjective past negative.')]),CourseSubchapter(number:'2.5',title:'Kapan dipakai',body:'Bandingkan register sopan dan biasa.',examples:[CourseExample('行きます。/ 行く。','Ikimasu. / Iku.','Pergi.','Sopan vs biasa.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — percakapan dan konteks informal'),
    CourseChapter(title:'Pengalaman & Pernah Melakukan',summary:'Menceritakan pengalaman, kejadian yang pernah dilakukan, dan daftar aktivitas masa lalu.',grammar:['Vたことがあります','Vたり Vたりします','ことがあります','まだ/もう pengantar'],terms:[CourseTerm('経験','keiken','pengalaman'),CourseTerm('旅行','ryokou','perjalanan'),CourseTerm('登る','noboru','mendaki'),CourseTerm('泳ぐ','oyogu','berenang'),CourseTerm('行ったことがある','itta koto ga aru','pernah pergi'),CourseTerm('食べたことがある','tabeta koto ga aru','pernah makan'),CourseTerm('見学','kengaku','kunjungan belajar')],examples:[CourseExample('日本へ 行ったことがあります。','Nihon e itta koto ga arimasu.','Saya pernah pergi ke Jepang.','Pengalaman.'),CourseExample('京都で お寺を 見たり、写真を 撮ったりしました。','Kyouto de otera o mitari, shashin o tottari shimashita.','Di Kyoto saya melihat kuil dan mengambil foto, dll.','Daftar aktivitas.')],subchapters:[CourseSubchapter(number:'3.1',title:'Pernah',body:'Vたことがあります untuk pengalaman setidaknya sekali.',examples:[CourseExample('富士山に 登ったことがあります。','Fujisan ni nobotta koto ga arimasu.','Pernah mendaki Gunung Fuji.','Pengalaman.')]),CourseSubchapter(number:'3.2',title:'Menyebut beberapa aktivitas',body:'Vたり Vたり untuk contoh kegiatan, bukan daftar lengkap.',examples:[CourseExample('映画を 見たり、本を 読んだりします。','Eiga o mitari, hon o yondari shimasu.','Saya menonton film, membaca buku, dan sebagainya.','Contoh kegiatan.')]),CourseSubchapter(number:'3.3',title:'Belum/pernah',body:'Bandingkan pengalaman yang sudah pernah dan yang belum.',examples:[CourseExample('まだ 行ったことがありません。','Mada itta koto ga arimasen.','Belum pernah pergi.','Negatif pengalaman.')]),CourseSubchapter(number:'3.4',title:'Percakapan pengalaman',body:'Tanya pengalaman orang lain.',examples:[CourseExample('日本料理を 食べたことがありますか。','Nihon ryouri o tabeta koto ga arimasu ka.','Pernah makan masakan Jepang?','Question pengalaman.')]),CourseSubchapter(number:'3.5',title:'Review',body:'Ceritakan tiga pengalaman dan satu yang belum pernah.',examples:[CourseExample('海外へ 行ったことが あります。','Kaigai e itta koto ga arimasu.','Pernah ke luar negeri.','Produksi.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — perjalanan dan pengalaman'),
    CourseChapter(title:'Keinginan, Kemampuan & Tujuan',summary:'Menyatakan keinginan, kemampuan, tujuan melakukan sesuatu, dan alasan memilih aktivitas.',grammar:['Vたいです','Vことができます','Nができます','V-stemに行く','Nのために pengantar'],terms:[CourseTerm('できる','dekiru','bisa'),CourseTerm('ほしい','hoshii','ingin'),CourseTerm('行きたい','ikitai','ingin pergi'),CourseTerm('見たい','mitai','ingin melihat'),CourseTerm('買いたい','kaitai','ingin membeli'),CourseTerm('勉強する','benkyou suru','belajar'),CourseTerm('練習する','renshuu suru','berlatih')],examples:[CourseExample('日本へ 行きたいです。','Nihon e ikitai desu.','Saya ingin pergi ke Jepang.','Keinginan.'),CourseExample('漢字を 読むことが できます。','Kanji o yomu koto ga dekimasu.','Bisa membaca kanji.','Kemampuan.'),CourseExample('映画を 見に 行きます。','Eiga o mi ni ikimasu.','Pergi untuk menonton film.','Tujuan.')],subchapters:[CourseSubchapter(number:'4.1',title:'Vたい',body:'Ubah stem ます ke bentuk たい untuk keinginan.',examples:[CourseExample('日本料理を 食べたいです。','Nihon ryouri o tabetai desu.','Saya ingin makan masakan Jepang.','Keinginan.')]),CourseSubchapter(number:'4.2',title:'Vことができます',body:'Menyatakan kemampuan secara eksplisit.',examples:[CourseExample('日本語で 話すことが できます。','Nihongo de hanasu koto ga dekimasu.','Bisa berbicara dalam bahasa Jepang.','Kemampuan.')]),CourseSubchapter(number:'4.3',title:'Tujuan pergi',body:'Stem + に行く untuk tujuan melakukan aksi.',examples:[CourseExample('本を 買いに 行きます。','Hon o kai ni ikimasu.','Pergi untuk membeli buku.','Purpose.')]),CourseSubchapter(number:'4.4',title:'Keinginan vs kemampuan',body:'Bedakan “ingin” dan “bisa”.',examples:[CourseExample('泳ぎたいです。','Oyogitai desu.','Saya ingin berenang.','Keinginan.'),CourseExample('泳ぐことが できます。','Oyogu koto ga dekimasu.','Saya bisa berenang.','Kemampuan.')]),CourseSubchapter(number:'4.5',title:'Review',body:'Buat rencana akhir pekan dengan satu keinginan dan satu tujuan.',examples:[CourseExample('映画を 見に 行きたいです。','Eiga o mi ni ikitai desu.','Saya ingin pergi menonton film.','Gabungan keinginan + tujuan.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — aktivitas, hobi, dan rencana'),
    CourseChapter(title:'Memberi, Menerima & Bantuan',summary:'Mengungkapkan siapa memberi apa kepada siapa dan siapa membantu siapa dengan struktur yang tepat.',grammar:['あげます','もらいます','くれます','Vてあげます','Vてもらいます'],terms:[CourseTerm('あげる','ageru','memberi'),CourseTerm('もらう','morau','menerima'),CourseTerm('くれる','kureru','memberi kepada saya/kelompok saya'),CourseTerm('貸す','kasu','meminjamkan'),CourseTerm('借りる','kariru','meminjam'),CourseTerm('教える','oshieru','mengajar/memberi tahu'),CourseTerm('習う','narau','belajar dari seseorang'),CourseTerm('手伝う','tetsudau','membantu')],examples:[CourseExample('友だちに 本を あげました。','Tomodachi ni hon o agemashita.','Saya memberi buku kepada teman.','Pemberi → penerima.'),CourseExample('先生に 日本語を 教えてもらいました。','Sensei ni Nihongo o oshiete moraimashita.','Saya diajari bahasa Jepang oleh guru.','Menerima bantuan.'),CourseExample('友だちが 手伝ってくれました。','Tomodachi ga tetsudatte kuremashita.','Teman membantu saya.','Kebaikan untuk pembicara.')],subchapters:[CourseSubchapter(number:'5.1',title:'Ageru',body:'Fokus pada arah memberi keluar dari pembicara.',examples:[CourseExample('妹に お菓子を あげました。','Imouto ni okashi o agemashita.','Saya memberi makanan ringan kepada adik.','Memberi.')]),CourseSubchapter(number:'5.2',title:'Morau',body:'Fokus pada penerima yang mendapatkan sesuatu.',examples:[CourseExample('友だちから 本を もらいました。','Tomodachi kara hon o moraimashita.','Saya menerima buku dari teman.','Menerima.')]),CourseSubchapter(number:'5.3',title:'Kureru',body:'Pemberi melakukan sesuatu untuk pembicara/kelompok pembicara.',examples:[CourseExample('母が 料理を 作ってくれました。','Haha ga ryouri o tsukutte kuremashita.','Ibu membuatkan makanan untuk saya.','Benefaktif.')]),CourseSubchapter(number:'5.4',title:'Vてもらう',body:'Menekankan bahwa pembicara menerima bantuan.',examples:[CourseExample('先生に 教えてもらいました。','Sensei ni oshiete moraimashita.','Saya diajari oleh guru.','Menerima tindakan.')]),CourseSubchapter(number:'5.5',title:'Review',body:'Buat tiga kalimat memberi/menerima dan satu kalimat bantuan.',examples:[CourseExample('友だちに 手伝ってもらいました。','Tomodachi ni tetsudatte moraimashita.','Saya dibantu teman.','Menerima bantuan.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — relasi sosial dan bantuan'),
    CourseChapter(title:'Perbandingan & Alasan',summary:'Membandingkan dua hal, menyatakan pilihan, memberi alasan, dan mengekspresikan perubahan sederhana.',grammar:['AよりBのほうが','AとBとどちら','一番','N/Adj + から','～くなる/～になる pengantar'],terms:[CourseTerm('より','yori','daripada'),CourseTerm('ほう','hou','sisi/pilihan'),CourseTerm('一番','ichiban','paling'),CourseTerm('同じ','onaji','sama'),CourseTerm('便利','benri','praktis'),CourseTerm('簡単','kantan','mudah'),CourseTerm('難しい','muzukashii','sulit'),CourseTerm('速い','hayai','cepat'),CourseTerm('遅い','osoi','lambat')],examples:[CourseExample('電車より バスのほうが 安いです。','Densha yori basu no hou ga yasui desu.','Bus lebih murah daripada kereta.','Perbandingan.'),CourseExample('夏と冬と どちらが 好きですか。','Natsu to fuyu to dochira ga suki desu ka.','Lebih suka musim panas atau dingin?','Memilih dua.'),CourseExample('日本語は おもしろいですから、勉強します。','Nihongo wa omoshiroi desu kara, benkyou shimasu.','Karena bahasa Jepang menarik, saya belajar.','Alasan.')],subchapters:[CourseSubchapter(number:'6.1',title:'Lebih ... daripada',body:'Gunakan より dan ほうが untuk membandingkan.',examples:[CourseExample('車より 電車のほうが 便利です。','Kuruma yori densha no hou ga benri desu.','Kereta lebih praktis daripada mobil.','Perbandingan.')]),CourseSubchapter(number:'6.2',title:'Memilih dua',body:'Tanya preferensi antara dua pilihan.',examples:[CourseExample('コーヒーと お茶と どちらが 好きですか。','Koohii to ocha to dochira ga suki desu ka.','Lebih suka kopi atau teh?','Pilihan dua.')]),CourseSubchapter(number:'6.3',title:'Paling',body:'Gunakan 一番 dalam kelompok.',examples:[CourseExample('この 店が 一番 安いです。','Kono mise ga ichiban yasui desu.','Toko ini paling murah.','Superlatif.')]),CourseSubchapter(number:'6.4',title:'Alasan',body:'Gunakan から untuk alasan langsung.',examples:[CourseExample('今日は 雨ですから、出かけません。','Kyou wa ame desu kara, dekakemasen.','Karena hari ini hujan, saya tidak keluar.','Sebab-akibat.')]),CourseSubchapter(number:'6.5',title:'Review',body:'Bandingkan dua cara transportasi dan jelaskan pilihanmu.',examples:[CourseExample('電車のほうが 速いですから、電車で 行きます。','Densha no hou ga hayai desu kara, densha de ikimasu.','Karena kereta lebih cepat, saya pergi naik kereta.','Perbandingan + alasan.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — pilihan, tempat, dan kehidupan sehari-hari'),
    CourseChapter(title:'Rencana & Masa Depan Dekat',summary:'Menyatakan jadwal, niat, rencana, undangan, dan keputusan.',grammar:['Vつもりです','V予定です','Vませんか','Vましょう','まだ/もう'],terms:[CourseTerm('予定','yotei','rencana/jadwal'),CourseTerm('つもり','tsumori','niat'),CourseTerm('約束','yakusoku','janji'),CourseTerm('予約','yoyaku','reservasi'),CourseTerm('準備','junbi','persiapan'),CourseTerm('決める','kimeru','memutuskan'),CourseTerm('参加する','sanka suru','berpartisipasi')],examples:[CourseExample('来月 日本へ 行くつもりです。','Raigetsu Nihon e iku tsumori desu.','Bulan depan saya berniat pergi ke Jepang.','Niat.'),CourseExample('土曜日に 友だちと 会う予定です。','Doyoubi ni tomodachi to au yotei desu.','Sabtu saya berencana bertemu teman.','Jadwal.'),CourseExample('いっしょに 勉強しませんか。','Issho ni benkyou shimasen ka.','Mau belajar bersama?','Undangan.')],subchapters:[CourseSubchapter(number:'7.1',title:'Niat',body:'Gunakan つもり untuk rencana personal.',examples:[CourseExample('今年、日本語を もっと 勉強するつもりです。','Kotoshi, Nihongo o motto benkyou suru tsumori desu.','Tahun ini saya berniat belajar bahasa Jepang lebih banyak.','Niat.')]),CourseSubchapter(number:'7.2',title:'Jadwal',body:'Gunakan 予定 untuk kegiatan yang sudah direncanakan.',examples:[CourseExample('来週、旅行する予定です。','Raishuu, ryokou suru yotei desu.','Minggu depan ada rencana bepergian.','Rencana.')]),CourseSubchapter(number:'7.3',title:'Undangan',body:'Gunakan ませんか dan respon penerimaan/penolakan.',examples:[CourseExample('映画を 見ませんか。','Eiga o mimasen ka.','Mau menonton film?','Undangan.')]),CourseSubchapter(number:'7.4',title:'Persiapan',body:'Tambahkan kosakata persiapan dan reservasi.',examples:[CourseExample('ホテルを 予約しました。','Hoteru o yoyaku shimashita.','Saya sudah memesan hotel.','Reservasi.')]),CourseSubchapter(number:'7.5',title:'Review',body:'Susun rencana akhir pekan dalam empat kalimat.',examples:[CourseExample('土曜日は 友だちに 会う予定です。','Doyoubi wa tomodachi ni au yotei desu.','Sabtu saya berencana bertemu teman.','Rencana.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — rencana dan aktivitas sosial'),
    CourseChapter(title:'Kondisi, Cuaca & Kesehatan',summary:'Mendeskripsikan kondisi fisik, cuaca, kesehatan, gejala sederhana, dan respons.',grammar:['どうしたんですか pengantar','～ています keadaan','～ので pengantar','Adjくて/で','Nが あります'],terms:[CourseTerm('天気','tenki','cuaca'),CourseTerm('晴れ','hare','cerah'),CourseTerm('雨','ame','hujan'),CourseTerm('雪','yuki','salju'),CourseTerm('風','kaze','angin'),CourseTerm('熱','netsu','demam'),CourseTerm('痛い','itai','sakit'),CourseTerm('元気','genki','sehat/bersemangat'),CourseTerm('薬','kusuri','obat'),CourseTerm('病院','byouin','rumah sakit')],examples:[CourseExample('今日は 雨が 降っています。','Kyou wa ame ga futte imasu.','Hari ini sedang hujan.','Keadaan berlangsung.'),CourseExample('頭が 痛いです。','Atama ga itai desu.','Kepala saya sakit.','Keluhan sederhana.'),CourseExample('薬を 飲んで、休んでください。','Kusuri o nonde, yasunde kudasai.','Minumlah obat dan istirahat.','Saran/instruksi.')],subchapters:[CourseSubchapter(number:'8.1',title:'Cuaca',body:'Bangun kosakata cuaca dan perubahan dasar.',examples:[CourseExample('今日は 晴れです。','Kyou wa hare desu.','Hari ini cerah.','Cuaca.')]),CourseSubchapter(number:'8.2',title:'Gejala',body:'Nyatakan bagian tubuh yang sakit dan kondisi.',examples:[CourseExample('おなかが 痛いです。','Onaka ga itai desu.','Perut saya sakit.','Gejala.')]),CourseSubchapter(number:'8.3',title:'Saran sederhana',body:'Gunakan permintaan sopan untuk perawatan.',examples:[CourseExample('病院へ 行ってください。','Byouin e itte kudasai.','Tolong pergi ke rumah sakit.','Saran/instruksi.')]),CourseSubchapter(number:'8.4',title:'Keadaan sedang',body:'Gunakan ています untuk kondisi yang sedang terjadi.',examples:[CourseExample('雨が 降っています。','Ame ga futte imasu.','Sedang turun hujan.','Keadaan.')]),CourseSubchapter(number:'8.5',title:'Review kesehatan',body:'Lakukan dialog pasien sederhana.',examples:[CourseExample('どうしたんですか。頭が 痛いです。','Dou shitan desu ka. Atama ga itai desu.','Ada apa? Kepala saya sakit.','Dialog kondisi.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — kehidupan sehari-hari dan kesehatan'),
    CourseChapter(title:'Membaca Informasi & Instruksi',summary:'Membaca pengumuman pendek, jadwal, instruksi, formulir, dan informasi praktis.',grammar:['Nがあります','Vてください','～なければなりません pengantar','～ないでください','Klausa sederhana'],terms:[CourseTerm('案内','annai','panduan/informasi'),CourseTerm('入口','iriguchi','pintu masuk'),CourseTerm('出口','deguchi','pintu keluar'),CourseTerm('受付','uketsuke','resepsionis/penerimaan'),CourseTerm('注意','chuui','perhatian'),CourseTerm('禁止','kinshi','dilarang'),CourseTerm('無料','muryou','gratis'),CourseTerm('有料','yuuryou','berbayar'),CourseTerm('必要','hitsuyou','perlu'),CourseTerm('営業時間','eigyou jikan','jam operasional')],examples:[CourseExample('ここは 入口です。','Koko wa iriguchi desu.','Ini pintu masuk.','Membaca label tempat.'),CourseExample('受付で 名前を 書いてください。','Uketsuke de namae o kaite kudasai.','Tolong tulis nama di resepsionis.','Instruksi.'),CourseExample('ここでは 写真を 撮らないでください。','Koko dewa shashin o toranaide kudasai.','Tolong jangan memotret di sini.','Larangan sopan.')],subchapters:[CourseSubchapter(number:'9.1',title:'Tanda tempat',body:'Kenali kosakata masuk, keluar, resepsionis, dan perhatian.',examples:[CourseExample('出口は あちらです。','Deguchi wa achira desu.','Pintu keluar di sana.','Informasi arah.')]),CourseSubchapter(number:'9.2',title:'Instruksi',body:'Baca perintah pendek dengan てください.',examples:[CourseExample('こちらで 待ってください。','Kochira de matte kudasai.','Tolong tunggu di sini.','Instruksi.')]),CourseSubchapter(number:'9.3',title:'Larangan',body:'Gunakan ないでください untuk larangan sopan.',examples:[CourseExample('ここで 食べないでください。','Koko de tabenaide kudasai.','Tolong jangan makan di sini.','Larangan.')]),CourseSubchapter(number:'9.4',title:'Informasi praktis',body:'Baca harga, jam buka, gratis/berbayar, dan kebutuhan.',examples:[CourseExample('入場は 無料です。','Nyuujou wa muryou desu.','Masuknya gratis.','Informasi harga.')]),CourseSubchapter(number:'9.5',title:'Review membaca',body:'Cari kata kunci sebelum menerjemahkan keseluruhan teks.',examples:[CourseExample('営業時間は 九時から 五時までです。','Eigyou jikan wa ku-ji kara go-ji made desu.','Jam operasional dari jam 9 sampai 5.','Membaca informasi.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — pengumuman dan informasi praktis'),
    CourseChapter(title:'Review N4 & Produksi',summary:'Menggabungkan grammar, vocabulary, reading, listening, dan produksi untuk memastikan fondasi N4 benar-benar dipakai.',grammar:['Review bentuk biasa','Vている','Vたことがある','Vたい/Vつもり','Perbandingan & alasan'],terms:[CourseTerm('復習','fukushuu','review'),CourseTerm('練習','renshuu','latihan'),CourseTerm('説明','setsumei','penjelasan'),CourseTerm('質問','shitsumon','pertanyaan'),CourseTerm('答え','kotae','jawaban'),CourseTerm('意味','imi','arti'),CourseTerm('文','bun','kalimat'),CourseTerm('会話','kaiwa','percakapan'),CourseTerm('読解','dokkai','pemahaman bacaan'),CourseTerm('聴解','choukai','pemahaman dengar')],examples:[CourseExample('日本語を 勉強するつもりです。','Nihongo o benkyou suru tsumori desu.','Saya berniat belajar bahasa Jepang.','Rencana.'),CourseExample('日本へ 行ったことがあります。','Nihon e itta koto ga arimasu.','Saya pernah pergi ke Jepang.','Pengalaman.'),CourseExample('電車のほうが 速いです。','Densha no hou ga hayai desu.','Kereta lebih cepat.','Perbandingan.')],subchapters:[CourseSubchapter(number:'10.1',title:'Mixed grammar',body:'Pilih pola berdasarkan fungsi, bukan kata kunci terjemahan.',examples:[CourseExample('明日は 行かないつもりです。','Ashita wa ikanai tsumori desu.','Besok saya berniat tidak pergi.','Negatif + niat.')]),CourseSubchapter(number:'10.2',title:'Vocabulary retrieval',body:'Panggil kata dari ingatan lalu masukkan ke kalimat.',examples:[CourseExample('毎日 日本語を 練習しています。','Mainichi Nihongo o renshuu shite imasu.','Saya latihan bahasa Jepang setiap hari.','Rutinitas.')]),CourseSubchapter(number:'10.3',title:'Reading',body:'Temukan siapa, kapan, di mana, dan apa yang terjadi.',examples:[CourseExample('土曜日に 駅で 会います。','Doyoubi ni eki de aimasu.','Bertemu di stasiun hari Sabtu.','Informasi inti.')]),CourseSubchapter(number:'10.4',title:'Listening',body:'Dengar kata kunci dan hubungan antar pembicara.',examples:[CourseExample('もう 一度 おねがいします。','Mou ichido onegaishimasu.','Sekali lagi, tolong.','Repair listening.')]),CourseSubchapter(number:'10.5',title:'Checkpoint N4',body:'Buat monolog singkat tentang diri, rutinitas, pengalaman, dan rencana.',examples:[CourseExample('わたしは 日本語を 勉強しています。日本へ 行ったことがあります。','Watashi wa Nihongo o benkyou shite imasu. Nihon e itta koto ga arimasu.','Saya sedang belajar bahasa Jepang. Saya pernah pergi ke Jepang.','Produksi terintegrasi.')])],imageUrl:n4Image,imageLabel:'Irodori Elementary 1 — konteks komunikasi nyata'),
  ];
}
